markdown: kramdown
rouge: pygments
kramdown:
  input: GFM
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: latelee
author: "李迟"
email: li@latelee.org
name: "李迟的个人主页"
url: https://latelee.github.io/
domain: https://latelee.github.io/
all_categories: [
["code", "程序","/posts/code.html"],
["linux", "linux","/posts/linux.html"],
["network", "网络","/posts/network.html"],
["mylife", "生活杂记","/posts/mylife.html"],
["about", "关于","/about.html"],
["resum", "简历","/resume.html"]
]
paginate: 10
paginate_path: "index_:num"
gems: [jekyll-paginate]
#paginate_path: "posts/page:num"
#gems:
# - jekyll-paginate

timezone: Asia/Shanghai

collections:
  docs:
    output: true

