markdown: kramdown
rouge: pygments
kramdown:
  input: GFM
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: latelee
author: "李迟"
email: li@latelee.org
name: "李迟的个人主页"
url: https://k.latelee.org

#baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://192.168.31.212:4000/" # the base hostname & protocol for your site

all_categories: [
["dailywork", "日常事务","/posts/dailywork.html"],
["team", "团队管理","/posts/team.html"],
["about", "关于","/about.html"],
#["resum", "简历","/resume.html"]
]
paginate: 5
paginate_path: "posts/page:num"
timezone: Asia/Shanghai

collections:
  docs:
    output: true

gems:
 - jekyll-paginate
