markdown: kramdown
rouge: pygments
kramdown:
  input: GFM
permalink: /posts/:title.html

# 文章摘要分隔符
excerpt_separator: "<!-- more -->"

title: 迟思堂工作室
subtitle: 李迟的个人主页
github: latelee
author: "李迟"
email: li@latelee.org

sit_info: 宠辱不惊，看庭前花开花落；去留无意，望天空云卷云舒

url: https://k.latelee.org
#url: https://k.latelee.org

baseurl: "" # the subpath of your site, e.g. /blog


all_categories: [
["南宁生活小贴士", "南宁生活小贴士","/pages/南宁生活小贴士.html"],
["常用小工具", "常用小工具","/pages/常用小工具.html"],
["about", "关于","/pages/about.html"],
["manual", "手册", "/manual/index.html"]
]
# 一个页面显示文件数量
paginate: 5
paginate_path: "posts/page:num"
timezone: Asia/Shanghai # 时区为东八区

collections:
  docs:
    output: true

gems:
 - jekyll-paginate
